import cjnTreePlotter
import xlrd



#alter this file  -> file name change blue look left top 角
#a={'house': {0: {'job': {0: 'no', 1: 'yes'}}, 1: 'yes'}}
if __name__ == '__main__':
    # 深度：9；叶子节点：84#alter this file  -> file name change blue look left top 角
    #a = {'age': {0: {'who': {0: 'medium shopper', 2: {'occupation': {0: 'heavy shopper', 3: 'medium shopper', 6: 'medium shopper'}}}}, 1: {'drinkDaily': {0: 'light shopper', 1: {'education': {0: 'medium shopper', 2: {'Member': {0: 'light shopper', 1: 'medium shopper'}}, 3: {'Transportation': {1: 'light shopper', 2: {'Income': {1: 'light shopper', 2: {'Member': {0: 'heavy shopper', 1: {'who': {0: 'medium shopper', 2: 'heavy shopper'}}}}, 3: 'light shopper'}}}}, 4: {'where': {0: 'medium shopper', 1: 'light shopper'}}, 5: 'heavy shopper'}}}}, 2: {'drinkDaily': {0: 'light shopper', 1: {'selfDrink': {0: 'light shopper', 1: {'gender': {0: 'light shopper', 1: {'education': {0: 'light shopper', 1: {'Transportation': {0: 'medium shopper', 1: 'light shopper', 2: {'married': {0: 'heavy shopper', 2: {'Member': {0: 'medium shopper', 1: 'light shopper'}}}}}}, 2: {'Income': {0: 'medium shopper', 2: 'light shopper', 3: 'medium shopper', 4: 'heavy shopper'}}, 3: {'Income': {0: 'medium shopper', 2: 'medium shopper', 3: {'married': {1: 'light shopper', 2: {'Member': {1: 'heavy shopper', 2: 'medium shopper'}}}}, 4: {'occupation': {0: 'light shopper', 1: 'heavy shopper'}}}}, 4: {'Member': {0: 'medium shopper', 1: {'Transportation': {0: 'heavy shopper', 2: {'occupation': {0: 'heavy shopper', 2: {'Income': {2: 'heavy shopper', 3: 'light shopper'}}}}}}}}}}, 2: {'Transportation': {1: 'light shopper', 2: 'medium shopper'}}}}}}}}, 3: {'Transportation': {0: 'heavy shopper', 1: 'light shopper', 2: {'married': {0: 'medium shopper', 1: 'heavy shopper', 2: {'selfDrink': {0: 'medium shopper', 1: {'gender': {0: 'light shopper', 1: {'Income': {0: {'Member': {0: 'heavy shopper', 1: 'medium shopper'}}, 1: 'light shopper', 2: {'who': {0: 'light shopper', 1: 'heavy shopper'}}, 3: 'medium shopper', 4: 'medium shopper', 6: 'light shopper'}}, 2: {'education': {2: 'heavy shopper', 3: 'light shopper', 4: 'medium shopper'}}}}}}}}}}, 4: {'drinkDaily': {0: 'light shopper', 1: {'Total volumes': {0.6: 'light shopper', 1.0: 'medium shopper', 2.4: 'heavy shopper', 2.64: 'heavy shopper', 0.625: 'light shopper', 0.66: 'light shopper', 0.99: 'medium shopper', 1.2: 'medium shopper', 7.5: 'heavy shopper', 1.98: 'medium shopper', 3.0: 'heavy shopper', 20.0: 'heavy shopper', 1.8: 'medium shopper', 0.33: 'light shopper'}}}}, 5: {'selfDrink': {0: 'medium shopper', 1: {'gender': {0: 'medium shopper', 1: {'Transportation': {0: 'light shopper', 2: {'education': {1: 'medium shopper', 4: 'heavy shopper'}}}}, 2: {'Member': {0: 'heavy shopper', 1: {'Transportation': {0: 'heavy shopper', 2: 'medium shopper'}}}}}}}}}}
    b = cjnTreePlotter.getNumLeafs(a)
    print(b)

